### ISSUE TITLE
lodash-node on package.json marked as * fail at runtime on OSX with newest version

### ISSUE THREAD

**Issue by thomasmodeneis** [jbrooksuk/node-summary#24]
Hi,
I've noticed that the loadash-node is marked as * on package.json, and because of this the newest version 3.6.0 is being downloaded when npm install. But this version fails at runtime with error: 
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash-node/underscore'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/tst/node_modules/node-summary/lib/summary.js:1:71)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

I changed the dependencies on packaje.json to 2.4.1 and is now all back to normal:
```
"dependencies": {
    "lodash-node": "2.4.1"
  }
```
Can you see if is possible to specify a proper working version instead of * ? that will help.

Thank you.

**Comment by jbrooksuk** [comment]
`lodas-node` now has a `lodash-node/compact` module we could import instead.
