### ISSUE TITLE
work with browserify

### ISSUE THREAD

**Issue by oa495** [jbrooksuk/node-summary#39]
https://wzrd.in/standalone/node-summary@1.2.0

```
Error: "browserify exited with code 1"

code: 1
stderr: Error: Parsing file /tmp/node-summary118116-28590-18ku69s/node_modules/node-summary/lib/summary.js: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
    at Deps.parseDeps (/home/admin/browserify-cdn/node_modules/browserify/node_modules/module-deps/index.js:454:28)
    at fromSource (/home/admin/browserify-cdn/node_modules/browserify/node_modules/module-deps/index.js:391:44)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/module-deps/index.js:385:17
    at ConcatStream.<anonymous> (/home/admin/browserify-cdn/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/home/admin/browserify-cdn/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at endWritable (/home/admin/browserify-cdn/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:485:3)
    at ConcatStream.Writable.end (/home/admin/browserify-cdn/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:41)
    at DuplexWrapper.onend (/home/admin/browserify-cdn/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:504:10)

```

**Comment by oa495** [comment]
duplicate of #37
